#version: '3.8'
#
#services:
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydatabase
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - my_bloom
#
#  app:
#    build: .
#    depends_on:
#      - db
#      - redis
#    ports:
#      - "5555:5555"
#    networks:
#      - my_bloom

#
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
##    volumes:
##      - cash:/
#    restart: always
#    networks:
#      - my_bloom

#
#
#networks:
#  my_bloom:



version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: